apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notiflex-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tmozii1/notiflex-platform.git
    targetRevision: main
    path: deploy/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: notiflex
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
